export type Plano = {
  id: string;
  nomePlano: string;
  categoria: string;
  regional: string;
};

export const planos: Plano[] = [
  { id: '1001', nomePlano: 'Plano Bronze Essencial', categoria: 'ADULTO', regional: 'SAO PAULO' },
  { id: '1002', nomePlano: 'Plano Prata Jovem', categoria: 'JOVEM', regional: 'RIO DE JANEIRO' },
  { id: '1003', nomePlano: 'Plano Ouro Sênior', categoria: 'SENIOR', regional: 'MINAS GERAIS' },
  { id: '1004', nomePlano: 'Plano Platina Executivo', categoria: 'ADULTO', regional: 'PARANA' },
  { id: '1005', nomePlano: 'Plano Diamante Negócios', categoria: 'ADULTO', regional: 'BAHIA' },
  { id: '1006', nomePlano: 'Plano Express Jovem', categoria: 'JOVEM', regional: 'PERNAMBUCO' },
  { id: '1007', nomePlano: 'Plano Flex Mais', categoria: 'ADULTO', regional: 'CEARA' },
  { id: '1008', nomePlano: 'Plano Especial Sênior', categoria: 'SENIOR', regional: 'RIO GRANDE DO SUL' },
  { id: '1009', nomePlano: 'Plano Start Jovem', categoria: 'JOVEM', regional: 'SANTA CATARINA' },
  { id: '1010', nomePlano: 'Plano Prime Empresas', categoria: 'ADULTO', regional: 'GOIAS' },
  { id: '1011', nomePlano: 'Plano Corporativo Norte', categoria: 'ADULTO', regional: 'AMAZONAS' },
  { id: '1012', nomePlano: 'Plano Capital Jovem', categoria: 'JOVEM', regional: 'DISTRITO FEDERAL' },
  { id: '1013', nomePlano: 'Plano Paulista Gold', categoria: 'ADULTO', regional: 'SAO PAULO' },
  { id: '1014', nomePlano: 'Plano Carioca Sênior', categoria: 'SENIOR', regional: 'RIO DE JANEIRO' },
  { id: '1015', nomePlano: 'Plano Mineiro Estudantil', categoria: 'JOVEM', regional: 'MINAS GERAIS' },
  { id: '1016', nomePlano: 'Plano Sul Premium', categoria: 'ADULTO', regional: 'PARANA' },
  { id: '1017', nomePlano: 'Plano Nordeste Plus', categoria: 'ADULTO', regional: 'BAHIA' },
  { id: '1018', nomePlano: 'Plano Recife Sênior', categoria: 'SENIOR', regional: 'PERNAMBUCO' },
  { id: '1019', nomePlano: 'Plano Ceará Connect', categoria: 'JOVEM', regional: 'CEARA' },
  { id: '1020', nomePlano: 'Plano Gaúcho Pro', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1021', nomePlano: 'Plano Catarinense Max', categoria: 'ADULTO', regional: 'SANTA CATARINA' },
  { id: '1022', nomePlano: 'Plano Goiás Smart', categoria: 'JOVEM', regional: 'GOIAS' },
  { id: '1023', nomePlano: 'Plano Amazônia Top', categoria: 'ADULTO', regional: 'AMAZONAS' },
  { id: '1024', nomePlano: 'Plano Brasília VIP', categoria: 'SENIOR', regional: 'DISTRITO FEDERAL' },
  { id: '1025', nomePlano: 'Plano Alpha Jovem', categoria: 'JOVEM', regional: 'SAO PAULO' },
  { id: '1026', nomePlano: 'Plano Beta Adulto', categoria: 'ADULTO', regional: 'RIO DE JANEIRO' },
  { id: '1027', nomePlano: 'Plano Gama Plus', categoria: 'ADULTO', regional: 'MINAS GERAIS' },
  { id: '1028', nomePlano: 'Plano Delta Jovem', categoria: 'JOVEM', regional: 'PARANA' },
  { id: '1029', nomePlano: 'Plano Ômega Sênior', categoria: 'SENIOR', regional: 'BAHIA' },
  { id: '1030', nomePlano: 'Plano Sigma Corp', categoria: 'ADULTO', regional: 'PERNAMBUCO' },
  { id: '1031', nomePlano: 'Plano Advance Jovem', categoria: 'JOVEM', regional: 'CEARA' },
  { id: '1032', nomePlano: 'Plano Master Adulto', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1033', nomePlano: 'Plano Ultra Flex', categoria: 'ADULTO', regional: 'SANTA CATARINA' },
  { id: '1034', nomePlano: 'Plano Conforto Sênior', categoria: 'SENIOR', regional: 'GOIAS' },
  { id: '1035', nomePlano: 'Plano Freedom Jovem', categoria: 'JOVEM', regional: 'AMAZONAS' },
  { id: '1036', nomePlano: 'Plano Federal Prime', categoria: 'ADULTO', regional: 'DISTRITO FEDERAL' },
  { id: '1037', nomePlano: 'Plano Sampa Connect', categoria: 'ADULTO', regional: 'SAO PAULO' },
  { id: '1038', nomePlano: 'Plano Rio Sênior Care', categoria: 'SENIOR', regional: 'RIO DE JANEIRO' },
  { id: '1039', nomePlano: 'Plano BH Jovem', categoria: 'JOVEM', regional: 'MINAS GERAIS' },
  { id: '1040', nomePlano: 'Plano Curitiba Pro', categoria: 'ADULTO', regional: 'PARANA' },
  { id: '1041', nomePlano: 'Plano Salvador Plus', categoria: 'ADULTO', regional: 'BAHIA' },
  { id: '1042', nomePlano: 'Plano Olinda Jovem', categoria: 'JOVEM', regional: 'PERNAMBUCO' },
  { id: '1043', nomePlano: 'Plano Fortaleza Sênior', categoria: 'SENIOR', regional: 'CEARA' },
  { id: '1044', nomePlano: 'Plano Porto Alegre Care', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1045', nomePlano: 'Plano Floripa Jovem', categoria: 'JOVEM', regional: 'SANTA CATARINA' },
  { id: '1046', nomePlano: 'Plano Goiânia Pro', categoria: 'ADULTO', regional: 'GOIAS' },
  { id: '1047', nomePlano: 'Plano Manaus Plus', categoria: 'ADULTO', regional: 'AMAZONAS' },
  { id: '1048', nomePlano: 'Plano Planalto Sênior', categoria: 'SENIOR', regional: 'DISTRITO FEDERAL' },
  { id: '1049', nomePlano: 'Plano Básico Jovem', categoria: 'JOVEM', regional: 'SAO PAULO' },
  { id: '1050', nomePlano: 'Plano Intermediário', categoria: 'ADULTO', regional: 'RIO DE JANEIRO' },
  { id: '1051', nomePlano: 'Plano Avançado Pro', categoria: 'ADULTO', regional: 'MINAS GERAIS' },
  { id: '1052', nomePlano: 'Plano Teen Start', categoria: 'JOVEM', regional: 'PARANA' },
  { id: '1053', nomePlano: 'Plano Melhores Anos Sênior', categoria: 'SENIOR', regional: 'BAHIA' },
  { id: '1054', nomePlano: 'Plano Empresarial Nordeste', categoria: 'ADULTO', regional: 'PERNAMBUCO' },
  { id: '1055', nomePlano: 'Plano Sol & Mar Jovem', categoria: 'JOVEM', regional: 'CEARA' },
  { id: '1056', nomePlano: 'Plano Pampas Pro', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1057', nomePlano: 'Plano Ilha Verde Max', categoria: 'ADULTO', regional: 'SANTA CATARINA' },
  { id: '1058', nomePlano: 'Plano Cerrado Sênior', categoria: 'SENIOR', regional: 'GOIAS' },
  { id: '1059', nomePlano: 'Plano Floresta Jovem', categoria: 'JOVEM', regional: 'AMAZONAS' },
  { id: '1060', nomePlano: 'Plano Esplanada Corp', categoria: 'ADULTO', regional: 'DISTRITO FEDERAL' },
  { id: '1061', nomePlano: 'Plano Jardins Gold', categoria: 'ADULTO', regional: 'SAO PAULO' },
  { id: '1062', nomePlano: 'Plano Barra Jovem', categoria: 'JOVEM', regional: 'RIO DE JANEIRO' },
  { id: '1063', nomePlano: 'Plano Savassi Sênior', categoria: 'SENIOR', regional: 'MINAS GERAIS' },
  { id: '1064', nomePlano: 'Plano Batel Pro', categoria: 'ADULTO', regional: 'PARANA' },
  { id: '1065', nomePlano: 'Plano Pelourinho Plus', categoria: 'ADULTO', regional: 'BAHIA' },
  { id: '1066', nomePlano: 'Plano Boa Viagem Jovem', categoria: 'JOVEM', regional: 'PERNAMBUCO' },
  { id: '1067', nomePlano: 'Plano Iracema Sênior', categoria: 'SENIOR', regional: 'CEARA' },
  { id: '1068', nomePlano: 'Plano Moinhos Adulto', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1069', nomePlano: 'Plano Beira Mar Jovem', categoria: 'JOVEM', regional: 'SANTA CATARINA' },
  { id: '1070', nomePlano: 'Plano Bueno Gold', categoria: 'ADULTO', regional: 'GOIAS' },
  { id: '1071', nomePlano: 'Plano Ponta Negra Plus', categoria: 'ADULTO', regional: 'AMAZONAS' },
  { id: '1072', nomePlano: 'Plano Asa Sul Sênior', categoria: 'SENIOR', regional: 'DISTRITO FEDERAL' },
  { id: '1073', nomePlano: 'Plano Pinheiros Jovem', categoria: 'JOVEM', regional: 'SAO PAULO' },
  { id: '1074', nomePlano: 'Plano Copacabana Adulto', categoria: 'ADULTO', regional: 'RIO DE JANEIRO' },
  { id: '1075', nomePlano: 'Plano Pampulha Pro', categoria: 'ADULTO', regional: 'MINAS GERAIS' },
  { id: '1076', nomePlano: 'Plano Juvevê Jovem', categoria: 'JOVEM', regional: 'PARANA' },
  { id: '1077', nomePlano: 'Plano Pituba Sênior', categoria: 'SENIOR', regional: 'BAHIA' },
  { id: '1078', nomePlano: 'Plano Espinheiro Plus', categoria: 'ADULTO', regional: 'PERNAMBUCO' },
  { id: '1079', nomePlano: 'Plano Meireles Jovem', categoria: 'JOVEM', regional: 'CEARA' },
  { id: '1080', nomePlano: 'Plano Bela Vista Adulto', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1081', nomePlano: 'Plano Agronômica Flex', categoria: 'ADULTO', regional: 'SANTA CATARINA' },
  { id: '1082', nomePlano: 'Plano Marista Sênior', categoria: 'SENIOR', regional: 'GOIAS' },
  { id: '1083', nomePlano: 'Plano Adrianópolis Jovem', categoria: 'JOVEM', regional: 'AMAZONAS' },
  { id: '1084', nomePlano: 'Plano Lago Sul Premium', categoria: 'ADULTO', regional: 'DISTRITO FEDERAL' },
  { id: '1085', nomePlano: 'Plano Morumbi Gold', categoria: 'ADULTO', regional: 'SAO PAULO' },
  { id: '1086', nomePlano: 'Plano Ipanema Jovem', categoria: 'JOVEM', regional: 'RIO DE JANEIRO' },
  { id: '1087', nomePlano: 'Plano Lourdes Sênior', categoria: 'SENIOR', regional: 'MINAS GERAIS' },
  { id: '1088', nomePlano: 'Plano Ecoville Pro', categoria: 'ADULTO', regional: 'PARANA' },
  { id: '1089', nomePlano: 'Plano Ondina Plus', categoria: 'ADULTO', regional: 'BAHIA' },
  { id: '1090', nomePlano: 'Plano Graça Jovem', categoria: 'JOVEM', regional: 'PERNAMBUCO' },
  { id: '1091', nomePlano: 'Plano Aldeota Sênior', categoria: 'SENIOR', regional: 'CEARA' },
  { id: '1092', nomePlano: 'Plano Petrópolis Adulto', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1093', nomePlano: 'Plano Jurerê Jovem', categoria: 'JOVEM', regional: 'SANTA CATARINA' },
  { id: '1094', nomePlano: 'Plano Oeste Pro', categoria: 'ADULTO', regional: 'GOIAS' },
  { id: '1095', nomePlano: 'Plano Vieiralves Plus', categoria: 'ADULTO', regional: 'AMAZONAS' },
  { id: '1096', nomePlano: 'Plano Sudoeste Sênior', categoria: 'SENIOR', regional: 'DISTRITO FEDERAL' },
  { id: '1097', nomePlano: 'Plano Moema Jovem', categoria: 'JOVEM', regional: 'SAO PAULO' },
  { id: '1098', nomePlano: 'Plano Leblon Premium', categoria: 'ADULTO', regional: 'RIO DE JANEIRO' },
  { id: '1099', nomePlano: 'Plano Mangabeiras Pro', categoria: 'ADULTO', regional: 'MINAS GERAIS' },
  { id: '1100', nomePlano: 'Plano Água Verde Jovem', categoria: 'JOVEM', regional: 'PARANA' },
  { id: '1101', nomePlano: 'Plano Rio Vermelho Sênior', categoria: 'SENIOR', regional: 'BAHIA' },
  { id: '1102', nomePlano: 'Plano Casa Forte Corp', categoria: 'ADULTO', regional: 'PERNAMBUCO' },
  { id: '1103', nomePlano: 'Plano Mucuripe Jovem', categoria: 'JOVEM', regional: 'CEARA' },
  { id: '1104', nomePlano: 'Plano Menino Deus Adulto', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1105', nomePlano: 'Plano Coqueiros Plus', categoria: 'ADULTO', regional: 'SANTA CATARINA' },
  { id: '1106', nomePlano: 'Plano Alpha Goiás Sênior', categoria: 'SENIOR', regional: 'GOIAS' },
  { id: '1107', nomePlano: 'Plano Amazonas Jovem', categoria: 'JOVEM', regional: 'AMAZONAS' },
  { id: '1108', nomePlano: 'Plano Águas Claras Pro', categoria: 'ADULTO', regional: 'DISTRITO FEDERAL' },
  { id: '1109', nomePlano: 'Plano Tatuapé Gold', categoria: 'ADULTO', regional: 'SAO PAULO' },
  { id: '1110', nomePlano: 'Plano Botafogo Jovem', categoria: 'JOVEM', regional: 'RIO DE JANEIRO' },
  { id: '1111', nomePlano: 'Plano Sion Sênior', categoria: 'SENIOR', regional: 'MINAS GERAIS' },
  { id: '1112', nomePlano: 'Plano Cabral Pro', categoria: 'ADULTO', regional: 'PARANA' },
  { id: '1113', nomePlano: 'Plano Graça Gold', categoria: 'ADULTO', regional: 'BAHIA' },
  { id: '1114', nomePlano: 'Plano Jaqueira Jovem', categoria: 'JOVEM', regional: 'PERNAMBUCO' },
  { id: '1115', nomePlano: 'Plano Cocó Sênior', categoria: 'SENIOR', regional: 'CEARA' },
  { id: '1116', nomePlano: 'Plano Três Figueiras Adulto', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1117', nomePlano: 'Plano Itacorubi Jovem', categoria: 'JOVEM', regional: 'SANTA CATARINA' },
  { id: '1118', nomePlano: 'Plano Jardim Goiás Pro', categoria: 'ADULTO', regional: 'GOIAS' },
  { id: '1119', nomePlano: 'Plano Dom Pedro Plus', categoria: 'ADULTO', regional: 'AMAZONAS' },
  { id: '1120', nomePlano: 'Plano Noroeste Sênior', categoria: 'SENIOR', regional: 'DISTRITO FEDERAL' },
  { id: '1121', nomePlano: 'Plano Perdizes Jovem', categoria: 'JOVEM', regional: 'SAO PAULO' },
  { id: '1122', nomePlano: 'Plano Flamengo Adulto', categoria: 'ADULTO', regional: 'RIO DE JANEIRO' },
  { id: '1123', nomePlano: 'Plano Anchieta Pro', categoria: 'ADULTO', regional: 'MINAS GERAIS' },
  { id: '1124', nomePlano: 'Plano Champagnat Jovem', categoria: 'JOVEM', regional: 'PARANA' },
  { id: '1125', nomePlano: 'Plano Caminho das Árvores Sênior', categoria: 'SENIOR', regional: 'BAHIA' },
  { id: '1126', nomePlano: 'Plano Madalena Corp', categoria: 'ADULTO', regional: 'PERNAMBUCO' },
  { id: '1127', nomePlano: 'Plano Dionísio Torres Jovem', categoria: 'JOVEM', regional: 'CEARA' },
  { id: '1128', nomePlano: 'Plano Higienópolis Adulto', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1129', nomePlano: 'Plano Córrego Grande Plus', categoria: 'ADULTO', regional: 'SANTA CATARINA' },
  { id: '1130', nomePlano: 'Plano Nova Suíça Sênior', categoria: 'SENIOR', regional: 'GOIAS' },
  { id: '1131', nomePlano: 'Plano Aleixo Jovem', categoria: 'JOVEM', regional: 'AMAZONAS' },
  { id: '1132', nomePlano: 'Plano Lago Norte Pro', categoria: 'ADULTO', regional: 'DISTRITO FEDERAL' },
  { id: '1133', nomePlano: 'Plano Santana Gold', categoria: 'ADULTO', regional: 'SAO PAULO' },
  { id: '1134', nomePlano: 'Plano Tijuca Jovem', categoria: 'JOVEM', regional: 'RIO DE JANEIRO' },
  { id: '1135', nomePlano: 'Plano Buritis Sênior', categoria: 'SENIOR', regional: 'MINAS GERAIS' },
  { id: '1136', nomePlano: 'Plano Ahú Pro', categoria: 'ADULTO', regional: 'PARANA' },
  { id: '1137', nomePlano: 'Plano Stella Maris Plus', categoria: 'ADULTO', regional: 'BAHIA' },
  { id: '1138', nomePlano: 'Plano Aflitos Jovem', categoria: 'JOVEM', regional: 'PERNAMBUCO' },
  { id: '1139', nomePlano: 'Plano Fátima Sênior', categoria: 'SENIOR', regional: 'CEARA' },
  { id: '1140', nomePlano: 'Plano Moinhos Gold', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1141', nomePlano: 'Plano Trindade Jovem', categoria: 'JOVEM', regional: 'SANTA CATARINA' },
  { id: '1142', nomePlano: 'Plano Eldorado Pro', categoria: 'ADULTO', regional: 'GOIAS' },
  { id: '1143', nomePlano: 'Plano Parque 10 Plus', categoria: 'ADULTO', regional: 'AMAZONAS' },
  { id: '1144', nomePlano: 'Plano Guará Sênior', categoria: 'SENIOR', regional: 'DISTRITO FEDERAL' },
  { id: '1145', nomePlano: 'Plano Vila Mariana Jovem', categoria: 'JOVEM', regional: 'SAO PAULO' },
  { id: '1146', nomePlano: 'Plano Laranjeiras Adulto', categoria: 'ADULTO', regional: 'RIO DE JANEIRO' },
  { id: '1147', nomePlano: 'Plano Castelo Pro', categoria: 'ADULTO', regional: 'MINAS GERAIS' },
  { id: '1148', nomePlano: 'Plano Bigorrilho Jovem', categoria: 'JOVEM', regional: 'PARANA' },
  { id: '1149', nomePlano: 'Plano Costa Azul Sênior', categoria: 'SENIOR', regional: 'BAHIA' },
  { id: '1150', nomePlano: 'Plano Derby Corp', categoria: 'ADULTO', regional: 'PERNAMBUCO' },
  { id: '1151', nomePlano: 'Plano Varjota Jovem', categoria: 'JOVEM', regional: 'CEARA' },
  { id: '1152', nomePlano: 'Plano Moinhos de Vento Adulto', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1153', nomePlano: 'Plano Centro Ilha Plus', categoria: 'ADULTO', regional: 'SANTA CATARINA' },
  { id: '1154', nomePlano: 'Plano Serrinha Sênior', categoria: 'SENIOR', regional: 'GOIAS' },
  { id: '1155', nomePlano: 'Plano Tarumã Jovem', categoria: 'JOVEM', regional: 'AMAZONAS' },
  { id: '1156', nomePlano: 'Plano Taguatinga Pro', categoria: 'ADULTO', regional: 'DISTRITO FEDERAL' },
  { id: '1157', nomePlano: 'Plano Santo Amaro Gold', categoria: 'ADULTO', regional: 'SAO PAULO' },
  { id: '1158', nomePlano: 'Plano Recreio Jovem', categoria: 'JOVEM', regional: 'RIO DE JANEIRO' },
  { id: '1159', nomePlano: 'Plano Gutierrez Sênior', categoria: 'SENIOR', regional: 'MINAS GERAIS' },
  { id: '1160', nomePlano: 'Plano Portão Pro', categoria: 'ADULTO', regional: 'PARANA' },
  { id: '1161', nomePlano: 'Plano Armação Plus', categoria: 'ADULTO', regional: 'BAHIA' },
  { id: '1162', nomePlano: 'Plano Parnamirim Jovem', categoria: 'JOVEM', regional: 'PERNAMBUCO' },
  { id: '1163', nomePlano: 'Plano Praia de Iracema Sênior', categoria: 'SENIOR', regional: 'CEARA' },
  { id: '1164', nomePlano: 'Plano Cidade Baixa Adulto', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1165', nomePlano: 'Plano Campeche Jovem', categoria: 'JOVEM', regional: 'SANTA CATARINA' },
  { id: '1166', nomePlano: 'Plano Alto da Glória Pro', categoria: 'ADULTO', regional: 'GOIAS' },
  { id: '1167', nomePlano: 'Plano São Jorge Plus', categoria: 'ADULTO', regional: 'AMAZONAS' },
  { id: '1168', nomePlano: 'Plano Vicente Pires Sênior', categoria: 'SENIOR', regional: 'DISTRITO FEDERAL' },
  { id: '1169', nomePlano: 'Plano Belém Jovem', categoria: 'JOVEM', regional: 'SAO PAULO' },
  { id: '1170', nomePlano: 'Plano Méier Adulto', categoria: 'ADULTO', regional: 'RIO DE JANEIRO' },
  { id: '1171', nomePlano: 'Plano Sagrada Família Pro', categoria: 'ADULTO', regional: 'MINAS GERAIS' },
  { id: '1172', nomePlano: 'Plano Santa Quitéria Jovem', categoria: 'JOVEM', regional: 'PARANA' },
  { id: '1173', nomePlano: 'Plano Brotas Sênior', categoria: 'SENIOR', regional: 'BAHIA' },
  { id: '1174', nomePlano: 'Plano Torre Corp', categoria: 'ADULTO', regional: 'PERNAMBUCO' },
  { id: '1175', nomePlano: 'Plano Benfica Jovem', categoria: 'JOVEM', regional: 'CEARA' },
  { id: '1176', nomePlano: 'Plano Passo d\'Areia Adulto', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1177', nomePlano: 'Plano Estreito Plus', categoria: 'ADULTO', regional: 'SANTA CATARINA' },
  { id: '1178', nomePlano: 'Plano Pedro Ludovico Sênior', categoria: 'SENIOR', regional: 'GOIAS' },
  { id: '1179', nomePlano: 'Plano Chapada Jovem', categoria: 'JOVEM', regional: 'AMAZONAS' },
  { id: '1180', nomePlano: 'Plano Sobradinho Pro', categoria: 'ADULTO', regional: 'DISTRITO FEDERAL' },
  { id: '1181', nomePlano: 'Plano Mooca Gold', categoria: 'ADULTO', regional: 'SAO PAULO' },
  { id: '1182', nomePlano: 'Plano Vila Isabel Jovem', categoria: 'JOVEM', regional: 'RIO DE JANEIRO' },
  { id: '1183', nomePlano: 'Plano Floresta Sênior', categoria: 'SENIOR', regional: 'MINAS GERAIS' },
  { id: '1184', nomePlano: 'Plano Hauer Adulto', categoria: 'ADULTO', regional: 'PARANA' },
  { id: '1185', nomePlano: 'Plano Cabula Plus', categoria: 'ADULTO', regional: 'BAHIA' },
  { id: '1186', nomePlano: 'Plano Casa Amarela Jovem', categoria: 'JOVEM', regional: 'PERNAMBUCO' },
  { id: '1187', nomePlano: 'Plano Parquelândia Sênior', categoria: 'SENIOR', regional: 'CEARA' },
  { id: '1188', nomePlano: 'Plano Cristal Adulto', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1189', nomePlano: 'Plano Capoeiras Jovem', categoria: 'JOVEM', regional: 'SANTA CATARINA' },
  { id: '1190', nomePlano: 'Plano Campinas Pro', categoria: 'ADULTO', regional: 'GOIAS' },
  { id: '1191', nomePlano: 'Plano Japiim Plus', categoria: 'ADULTO', regional: 'AMAZONAS' },
  { id: '1192', nomePlano: 'Plano Ceilândia Sênior', categoria: 'SENIOR', regional: 'DISTRITO FEDERAL' },
  { id: '1193', nomePlano: 'Plano Lapa Jovem', categoria: 'JOVEM', regional: 'SAO PAULO' },
  { id: '1194', nomePlano: 'Plano Campo Grande Adulto', categoria: 'ADULTO', regional: 'RIO DE JANEIRO' },
  { id: '1195', nomePlano: 'Plano Caiçara Pro', categoria: 'ADULTO', regional: 'MINAS GERAIS' },
  { id: '1196', nomePlano: 'Plano Boqueirão Jovem', categoria: 'JOVEM', regional: 'PARANA' },
  { id: '1197', nomePlano: 'Plano Imbuí Sênior', categoria: 'SENIOR', regional: 'BAHIA' },
  { id: '1198', nomePlano: 'Plano Imbiribeira Corp', categoria: 'ADULTO', regional: 'PERNAMBUCO' },
  { id: '1199', nomePlano: 'Plano Montese Jovem', categoria: 'JOVEM', regional: 'CEARA' },
  { id: '1200', nomePlano: 'Plano Partenon Adulto', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  
  // Registros de 1201 até 1500 compactados dinamicamente com nomes de planos fictícios
  ...Array.from({ length: 300 }).map((_, i) => {
    const tipos = ['Plano Bronze', 'Plano Prata', 'Plano Ouro', 'Plano Platina', 'Plano Diamante', 'Plano Titanium', 'Plano Flex', 'Plano Smart', 'Plano Plus', 'Plano Premium', 'Plano Express', 'Plano Max', 'Plano VIP', 'Plano Executivo', 'Plano Master'];
    const segmentos = ['Essencial', 'Empresarial', 'Confeccao', 'Digital', 'Pro', 'Corp', 'Connect', 'Care', 'Advance', 'Ultra', 'Top', 'Capital', 'Prime', 'Start', 'Freedom'];
    const categorias = ['JOVEM', 'ADULTO', 'SENIOR'];
    const regionais = ['SAO PAULO', 'RIO DE JANEIRO', 'MINAS GERAIS', 'PARANA', 'BAHIA', 'PERNAMBUCO', 'CEARA', 'RIO GRANDE DO SUL', 'SANTA CATARINA', 'GOIAS', 'AMAZONAS', 'DISTRITO FEDERAL'];
    
    return {
      id: (1201 + i).toString(),
      nomePlano: `${tipos[i % tipos.length]} ${segmentos[(i + 3) % segmentos.length]} ${i + 1}`,
      categoria: categorias[i % categorias.length],
      regional: regionais[i % regionais.length]
    };
  })
];

export function obterNomePlanoAleatorio(): string {
  const planoAleatorio = planos[Math.floor(Math.random() * planos.length)];
  return planoAleatorio.nomePlano;
}